spring:
  application:
    name: customerservice
  cloud:
    config:
      profile: dev
  config:
    import: configserver:http://localhost:8050/

    #ConfigServerin application.yml'ına git. Orası Git'e bağlanıyor. Gitdeki customerservice.dev dosyasını config
    #ayarı olarak al.