server:
  port: 8050

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dogukankoc/CrmConfiguration.git

#Config ayarlar?n? bu git reposundan al
